baseurl = "https://derreineke.com/"
languageCode = "en-us"
title = "Reineke Fuchs"
paginate = 4
theme = "sublime-hugo-theme"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Reineke Fuchs"
	description = "Portfolio of Reineke Fuchs"
	copyright = "2019 Reineke Fuchs"

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "The requested page was not <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Reineke Fuchs"
	bio = "Just a Heckermin who is interested in Programming, Cybersecurity, and Data Science"
	bio2 = "Near Hannover, Germany"
	followme = "Contact"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "derreineke@protonmail.com"
        url = "mailto:derreineke@protonmail.com"
        github = "https://github.com/derReineke"
        git = "derReineke"
        linkedin = "https://www.linkedin.com/in/derreineke/"